# Generated by Django 4.1.6 on 2023-02-26 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_amenities_alter_room_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="torilets",
            new_name="toilets",
        ),
    ]
