# Generated by Django 4.1.6 on 2023-02-27 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0003_alter_experience_perks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perk",
            options={"verbose_name_plural": "Perks"},
        ),
    ]
