# Generated by Django 4.1.6 on 2023-02-07 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="Chattingroom",
            new_name="room",
        ),
    ]
