# Generated by Django 4.1.6 on 2023-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="kind",
            field=models.CharField(
                choices=[("room", "Room"), ("experience", "Experience")], max_length=15
            ),
        ),
    ]
